name: Build
on:
  push:
    branches: [ master, actions ]
  pull_request:
    branches: [ master, actions ]
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: windows-latest
            name: "Windows x64 MSVC"
            artifact: "Windows-MSVC.tar.xz"
            build_type: "RelWithDebInfo"
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
            cc: "cl"
            cxx: "cl"
            archiver: "7z a"
            generators: "Visual Studio 16 2019"
            build_dir: 'build'
          #- os: ubuntu-latest
          #  name: "Ubuntu GCC-11"
          #  artifact: "ubuntu_gcc.7z"
          #  build_type: "RelWithDebInfo"
          #  cc: "gcc-11"
          #  cxx: "g++-11"
          #  archiver: "7z a"
          #  generators: "Unix Makefiles"
          #  build_dir: 'build'

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          
      - name: Setup
        id: setup
        uses: Silverlan/common_actions/setup@actions
        
      - name: Install GCC-11
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install gcc-11 g++-11
          
      - name: Download binaries
        uses: Silverlan/common_actions/download_build_binaries@actions
        continue-on-error: true

      - name: Download common external libs
        uses: Silverlan/common_actions/get_common_external_libs@actions
        
      - name: Download submodule - lz4
        uses: Silverlan/common_actions/get_submodule@main
        with:
          dir: 'third_party_libs'
          repo: 'https://github.com/lz4/lz4.git'
          repo_name: 'lz4'
          repo_branch: 'release'
          
      - name: CMake Build
        uses: Silverlan/common_actions/build_cmake@actions
        with:
          build_target: util_udm
          build_type: ${{ matrix.config.build_type }}
          build_generator: ${{ matrix.config.generators }}
          
      - name: Upload binaries
        uses: Silverlan/common_actions/upload_build_binaries@actions
          
